name: entorno_api
dependencies:
  - python>=3.10
  - pip
  - wheel
  - setuptools
  - pip:
      - pandas>=2.2.3,<=3.0.3
      - numpy
      - scikit-learn
      - joblib
      - xgboost
      - matplotlib
      - pydataxm
      - requests
      - aiohttp
      - asyncio
      - nest_asyncio
